name: Build iOS IPA
on: [push]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Fastlane
  run: |
    sudo gem install bundler
    BUNDLE_GEMFILE=$GITHUB_WORKSPACE/Gemfile bundle install
    cd $GITHUB_WORKSPACE    # 确保进入仓库根目录
    bundle install
      - name: Build IPA
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: |
          fastlane build_ipa
